language: node_js
node_js: node
services: mongodb
deploy:
  provider: heroku
  api_key:
    secure: oYRXmMbcfu/Cqkea/oigo5AynTNcKbZZ7cCcBA7RI8KRAujqIAbCPqgk3jjq40PJXhbXwMViMFVfYEwv5ev5WyyQdjYEzSMX6g+0/pSyRO2yoosveuaXQTUGbPIN3G7Jq97rRlarn3EbnESGv4Tw+VOr2jFXqUTvCsrWVkfwD2Hutq+cNOBPLz8N2AovSnVqspMOrROvI23uyJASRwDTtP2hvPHmNGyt2zgnBEiCTmiOCu6h/F3mE9V4rp5U6MZrzWad+XzkF82FiQe3VyNbb3Bc/QNVtD/lzuDjwPpqvgvjuVJvuzecps06Fbk9ucf/I31f01gWpCt0OoMKA4VW7nj8cguvbcG6t6Qfdgj4mvrY8o8+vLkaevbiz7V7f58RcIDqJk/QyOmpnC9t9P85UTCD4wwObLYdz6c2NT4ooxTWjFcyJcqWWKi+hcGyCkdoyhqVp7pjI6Z3PodFHQ7ZFplprvPEkznoKIGNdAnJ0rtVlkTkiNn4SWaedBipRupoPiO1ajhEnjj6OXYfSnLlaZFaln5CFaZvu9V3KlnWBgdiWHbebARSZB+KZTyzT156rFXKMt1pF/klgAldXCHS7OAX4dliY1UemT7I2qxcVc+ahwH4eg/hjskpXWO8plnkajHpdcQu0FmvzcbgJLyeB5QfzpK50PyGbJOvT1v8dOQ=
  app: peaceful-forest-69699
  on:
    repo: owcollier/Wizardly-5e
